Repository ManageIQ/ruby-rpm-ffi2, pull requests merged in 2025-01, with the labels that each got.

#5 Detect librpm.so.9
  lib/rpm/c.rb
Labels: enhancement

#4 Do not use headerNVR in Package.version
  lib/rpm/package.rb
  test/test_package.rb
  test/test_transaction.rb
Labels: bug

#8 Add workflow_dispatch to GitHub action
  .github/workflows/ci.yaml
Labels: test

#10 Expose rake tasks to rake -T
  Rakefile
Labels: developer, enhancement

#11 Cleanup warnings
  lib/rpm.rb
  lib/rpm/c/rpmio.rb
  lib/rpm/c/rpmts.rb
  lib/rpm/package.rb
  lib/rpm/transaction.rb
  lib/rpm/version.rb
  test/test_file.rb
  test/test_package.rb
  test/test_problem.rb
  test/test_rpm.rb
Labels: technical debt

#13 Add timeout-minutes: 5 to CI workflow
  .github/workflows/ci.yaml
Labels: test

#14 Add CODEOWNERS
  .github/CODEOWNERS
Labels: developer

#16 Split tests by platform
  .github/workflows/ci.yaml
  Rakefile
Labels: test

#17 Force the platform to linux/amd64 in tests
  Rakefile
  _docker/Dockerfile.ubi8
  _docker/Dockerfile.ubi9
Labels: bug, test
